---
name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: gradle build javadoc
      - name: Commit doc files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mv build/docs/javadoc docs
          git add docs
          git commit -m "Generate Javadoc"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: 'true'
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
           path: "./build/libs/publish_artifact.jar"
           name: "publish_artifact.jar"
